# Normally this file should not be commited to repo. But for learning purposes, we are committing it.


apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data: # values must be base64 encoded
  db-username: cHJhc2FubmE=  # "prasanna" # `echo -n 'your-word' | base64` 
  db-password: cGFzc3dvcmQ=  # "W3lc0m3"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
  labels:
    app: mongo-express
data:
  mongo-db-service: "db-service"
