apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: my-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-db
  template: 
    metadata:
      labels:
        app: my-db
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          #value: something       
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          #value:        
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db-password

--- # This is a separator between different resources

apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: my-db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017 
      # Just opens the port for the service, not a load balancer